Add custom job documentation
timescale/docs.timescale.com-content pull request #498
Opened 2020-09-17 18:37 UTC by svenklemm

2020-09-18 16:45 UTC, svenklemm commented on using-timescaledb/custom_jobs.md
> +# Custom Jobs
@mfreed Should we call this custom policies?

2020-09-21 11:07 UTC, k-rus requested changes
Great start! Few notices:

This PR introduces new doc page. Can you make this page reachable? It seems to me it should be added to the TOC, so it appears in using section. If I don't mistake, this page needs to be updated https://github.com/timescale/docs.timescale.com-content/blob/master/page-index/page-index.js

Existing pages in Using section describes code examples before the code. I think this page should not be an exception.

Another comment that this page should link to function descriptions in API doc. I guess it is necessary to guess the links until the other page is added.

Can you added the examples as regression tests to TimescaleDB if it wasn't done yet?

2020-09-21 11:07 UTC, k-rus commented on using-timescaledb/custom_jobs.md
> +## Generic Retention Policy
I suggest to have a separate section for examples and then level down each example. For example:
```suggestion
## Examples of custom policies

This section provides several example how to create custom policies.

### Generic Retention Policy
```

2020-09-21 11:07 UTC, k-rus commented on using-timescaledb/custom_jobs.md
> +
Can you describe the example before the code, so it will be easier for the reader to follow the code?

2020-09-21 11:07 UTC, k-rus commented on using-timescaledb/custom_jobs.md
> +	PERFORM drop_chunks(format('%I.%I',table_schema,table_name), older_than => lag) FROM timescaledb_information.hypertables;
Should it be the same indentation as `IF`?

2020-09-21 11:36 UTC, closed without merging