Remove gucs specific to planning
timescale/docs.timescale.com-content pull request #561
Opened 2020-10-26 22:24 UTC by gayyappan

These gucs are for internal use only.

2020-10-26 22:51 UTC, mfreed approved these changes

2020-10-27 01:26 UTC, ryanbooz commented
It's up to you how you want to handle this PR, but I had already moved this file and removed some of these based on @gayyappan 's comment in Slack. Might be easier just to review my chances to make sure I remove all of them?

2020-10-27 13:22 UTC, ryanbooz requested changes
I had already moved this page in another branch to fix some other 2.0 documentation changes. Initial PR #565

2020-10-27 13:43 UTC, gayyappan commented
> It's up to you how you want to handle this PR, but I had already moved this file and removed some of these based on @gayyappan 's comment in Slack. Might be easier just to review my chances to make sure I remove all of them?

That works. I'll close this PR.

2020-10-27 13:43 UTC, closed without merging